### ISSUE TITLE
Tehtävien palautuksen merkitseminen

### ISSUE THREAD

**Issue by Jhoneagle** [mluukkai/Ohjelmistotuotanto2018#10]
Ensimmäisen viikon laskareissa löytyvä linkki (https://studies.cs.helsinki.fi/courses/ohtu2018) johtaa raakaan json-tiedostoon. Joten miten palautuksen merkitsemisen on tarkoitus käytännössä tapahtua?

**Comment by nigoshh** [comment]
https://studies.cs.helsinki.fi/courses/#/ohtu2018
