### ISSUE TITLE
It is possible to submit several submissions for one week.

### ISSUE THREAD

**Issue by EssKayz** [mluukkai/Ohjelmistotuotanto2018#245]
So I was trying to fix my submission, because I had accidentally ticked one excercise too little, and this happened :

![image](https://user-images.githubusercontent.com/11611514/48673472-8bc74600-eb4a-11e8-8381-e92001aa1813.png)

**Comment by mluukkai** [comment]
yes, this is a known issue. will be fixed later on... shall remove the extra submission
